### ISSUE TITLE
萌新求助

### ISSUE THREAD

**Issue by 18205698790** [Laughing-q/yolov5_annotations#1]
大佬您的YOLOv5的注解真的好详细呀，非常感谢！顺便请问一下您有做Scaled-YOLOv4的注释吗？最近在学习Scaled-YOLOv4，但作为一个萌新，感觉要看懂好难，您有什么学代码的诀窍吗？想向您请教一下，谢谢。

**Comment by Laughing-q** [comment]
@18205698790 scaled_yolov4不在计划当中哈，这个更新yolov5也是之前csdn有读者评论问我什么时候更新哈哈，顺便yolov5更新蛮多的了，所以就顺便更新一波；scaled-yolov4我没记错是基于yolov5的吧，应该好多代码这边的注释也管用；学代码就是多看大佬的代码，多学习多思考吧，刚开始是挺难的，加油

**Comment by 18205698790** [comment]
> @18205698790 scaled_yolov4不在计划当中哈，这个更新yolov5也是之前csdn有读者评论问我什么时候更新哈哈，顺便yolov5更新蛮多的了，所以就顺便更新一波；scaled-yolov4我没记错是基于yolov5的吧，应该好多代码这边的注释也管用；学代码就是多看大佬的代码，多学习多思考吧，刚开始是挺难的，加油

**Comment by 18205698790** [comment]
好的，谢谢您！
